[environments]
  [environments.development]
    name = "golang"
    namespace = "default"
    wait = false
    watch = false
    watch-delay = 2
    auto-connect = false
    override-ports = ["8081:8080", "2345:2345"]
    dockerfile = "Dockerfile.debug"
    chart = "go"