apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: debug-service
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.serviceCatalogEnv }}
        env:
{{- range $index, $value := .Values.serviceCatalogEnv }}
{{- range $key := $value.vars }}
          - name: {{ $value.name | upper }}_{{ . | upper }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.name }}
                key: {{ . }}
{{- end }}
{{- end }}
{{- end }}